spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos 服务器地址
        username: nacos
        password: nacos
        namespace: dev
  application:
    name: gateway  # 当前服务名
server:
  port: 10000
